### ISSUE TITLE
java.io.FileNotFoundException: WEB-INF/logging.properties (No such file or directory)

### ISSUE THREAD

**Issue by 779503982** [GoogleCloudPlatform/firebase-appengine-backend#10]
I tried to deploy this project on google app engine but couldn't get it work. I've set up the firebase project, acquired service account, enabled the billing on google app engine, and set the project with gcloud command. The error reads:

[INFO] Updating service [default] (this may take several minutes)...
[INFO] .................................................................................................................................................................failed.
[INFO] ERROR: (gcloud.app.deploy) Error Response: [9] 
[INFO] Application startup error:
[INFO] Info: Limiting Java heap size to: 400M
[INFO] 2018-01-13 00:11:30.918:INFO::main: Logging initialized @523ms
[INFO] 2018-01-13 00:11:32.641:INFO:oejs.Server:main: jetty-9.3.5.v20151012
[INFO] 2018-01-13 00:11:33.029:INFO:oejs.AbstractNCSARequestLog:main: Opened /var/log/app_engine/request.2018_01_13.log
[INFO] Jan 13, 2018 12:11:34 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
[INFO] INFO: Meta-data 'attributes/gae_affinity' path retrieval error: http://metadata/computeMetadata/v1/instance/attributes/gae_affinity
[INFO] Jan 13, 2018 12:11:34 AM com.google.apphosting.vmruntime.VmMetadataCache getMetadata
[INFO] INFO: Meta-data 'attributes/gae_appengine_hostname' path retrieval error: http://metadata/computeMetadata/v1/instance/attributes/gae_appengine_hostname
[INFO] Warning: caught exception when reading logging properties.
[INFO] java.io.FileNotFoundException: WEB-INF/logging.properties (No such file or directory)
[INFO] 
[ERROR] Error: gcloud app command with exit code : 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:05 min
[INFO] Finished at: 2018-01-12T19:12:10-05:00
[INFO] Final Memory: 25M/83M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:2.0.9.121.v20160815:deploy (default-cli) on project backend: Error: gcloud app command exit code is: 1 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Could someone please help me? Is this because I used the database on Firebase of my other project? I've spent days on this and really hope I can get this example rolling to use google app engine for my own app. Any reply would be greatly appreciated!

**Comment by Ricalo** [comment]
Hi 779503982@

I recently updated this project, could you pull the changes and try to deploy with the new command:

```
mvn clean package appengine:deploy
```

Otherwise it might be a problem with the Docker image. Please try the updated code sample and let me know.
