### ISSUE TITLE
Error running local server: GCLOUD: agent library failed to init:instrument

### ISSUE THREAD

**Issue by ricalo** [GoogleCloudPlatform/firebase-appengine-backend#21]
To run the sample in the local service:

```
mvn clean package appengine:run
```

The command fails with the following message:
```
May 23, 2019 12:22:18 PM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: /usr/local/buildtools/java/jdk8-google-v7-64/jre/bin/java -javaagent:/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/agent/appengine-agent.jar -Dappengine.sdk.root=/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java -cp /usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com.google.appengine.tools.development.DevAppServerMain --allow_remote_shutdown --disable_update_check ~/firebase-appengine-backend/target/backend
[INFO] GCLOUD: Error opening zip file or JAR manifest missing : /usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/agent/appengine-agent.jar
[INFO] GCLOUD: Error occurred during initialization of VM
[INFO] GCLOUD: agent library failed to init: instrument
```

gcloud version: 247.0.0
app-engine-java version: 1.9.74

**Comment by ricalo** [comment]
The issue seems to have been introduced in gcloud version `241.0.0` .

The command to start the local server runs successfully after downgrading to version `240.0.0`:
```
gcloud components update --version 240.0.0
```
In summary:

| gcloud | app-engine-java | result |
|----------|----------------------|---------|
| 241.0.0 | 1.9.73 | fail |
| 240.0.0 | 1.9.72 | success |

**Comment by edgedalmacio** [comment]
This is still an issue on gcloud version 274. Even when I have downgraded to 240, whenever I try to run `appengine-maven-plugin:run`, gcloud automatically updates to the latest gcloud version which then goes back to this problem.

**Comment by edgedalmacio** [comment]
Added `<cloudSdkVersion>240.0.0</cloudSdkVersion>` to my pom and it worked.

**Comment by jmayday** [comment]
I had similar issue: https://github.com/GoogleCloudPlatform/getting-started-java/issues/513
