### ISSUE TITLE
Finally Got the Guide working. (Windows 10)

### ISSUE THREAD

**Issue by peterwjames** [GoogleCloudPlatform/firebase-appengine-backend#4]
There appears, to run locally you are required to install 'Python 2.7' (NOT 3.5.2).

Or at least change your system variables so the 'python' CMD is a recognised command. 

Without both installed I would get 'python' not recongised command error.

With 3.5.2 installed, it appears the execfile was removed.

http://stackoverflow.com/questions/6357361/alternative-to-execfile-in-python-3

---

I would advise someone to run through this guide on a cleanly built version of Windows 10 (With nothing installed) and see how much of a headache to get this Tutorial working is.

**Comment by Ricalo** [comment]
Hi @peterwjames,

Sorry you ran into issues trying this sample.

I just tried the code sample on Windows using the instructions on [Build an Android App Using Firebase and the App Engine Flexible Environment](https://cloud.google.com/solutions/mobile/mobile-firebase-app-engine-flexible), which provides more detail than the ReadMe in this repo.

I had no issues after I had all the prerequisites installed. However, I agree that the ReadMe in this repo should at least list the prerequisites to build and run the sample. I submitted PR #15 to include the Java and Python prerequisites to the ReadMe.
