### ISSUE TITLE
project uses deprecated Managed VMs beta environment

### ISSUE THREAD

**Issue by stahlmagnat** [GoogleCloudPlatform/firebase-appengine-backend#9]
This project is referenced in guide : https://cloud.google.com/solutions/mobile/mobile-firebase-app-engine-flexible, but is using a deprecated Managed VMs beta environment.

Google sends out E-Mails like this to Firebase users who use this project as a basis. Means it will not work anymore at all on dec 15 2017?  

"This is a reminder that the Managed VMs beta environment (App Engine applications deployed with vm: true in their app.yaml) is deprecated and will be turned down on December 15, 2017. The App Engine flexible environment is replacing Managed VMs, which we are no longer updating."

... 

"Action required: Please visit the upgrade guide, and learn more about how to move from the vm: true environment to the env: flex environment. The following projects have active App Engine Managed VM versions currently running, and those versions will be stopped on December 15, 2017:"

Since no app.yaml is in use here (appengine.xml) and the google migration guide https://cloud.google.com/appengine/docs/flexible/java/upgrading does not reference Firebase at all, it would be fantastic if this project, or the documentation could be updated as well...
Thanks!

**Comment by stahlmagnat** [comment]
I think it's an overall problem switching from vm to flex and migrate your stuff...

[api-call-failed-from-app-engine-flexible-to-firebase](https://stackoverflow.com/questions/48036472/api-call-from-app-engine-flexible-to-firebase-fcm)

**Comment by 779503982** [comment]
Could someone please update the project with "env: flex"? There must be some nuances that I don't know. I tried to use app.yaml with "env: flex" and replaced appengine-web.xml with it, and I also changed all "vm: true" in all app.yaml files under the directory, but it won't work. It still shows the error "Deployments to App Engine Flexible require `env: flex` in app.yaml.  The `vm:true` setting has been deprecated". I guess there is some file writing "vm: true" to an app.yaml under directory "appengine-staging". I really want an example working with firebase and google cloud app engine in java. Please help. Thank you guys very much!!!!!!!!!

**Comment by Ricalo** [comment]
Apparently, this was fixed in #8 on Dec 2017. Please let me know if you continue having this issue.
